### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by SaulDoesCode** [BrodaNoel/duix#5]
```js
const store = Object.create(null)

export default ((host = Object.create(null), subs = new Map()) => Object.assign(host, {
    emit(event, ...data) {
        if (subs.has(event)) for (const h of subs.get(event)) h.apply(null, data)
    },
    subscribe(event, handler) {
        if (!(handler instanceof Function)) throw new TypeError('subs need functions')
        if (!subs.has(event)) subs.set(event, new Set())
        subs.get(event).add(handler)
        return () => host.unsubscribe(event, handler)
    },
    unsubscribe (event, handler) {
        if (!subs.has(event)) return
        const ls = subs.get(event)
        ls.delete(handler)
        if (!ls.size) subs.delete(event)
    },
    set(key, val) {
        const old = store[key]
        if (old != null && old === val) return
        host.emit(key, store[key] = val, old)
    },
    get: key => store[key]
}))()
```

**Comment by BrodaNoel** [comment]
Hi @SaulDoesCode!
Thank you for creating this issue and sharing your idea.

Could you please elaborate a bit about what is the idea that you are proposing here?
- Are you solving a problem?
- Are you improving code performance?
- Are you improving code readability?

I'll appreciate it!

On another hand, please check that the Readme talks about the KISS principle (If you don't know what this means, please check this Wikipedia link: [KISS = Keep it simple, stupid](https://en.wikipedia.org/wiki/KISS_principle)) (BTW, sorry for the "stupid" but, that the Principle name heheha).
If I compare your code, and the original code, I can say that my code can be read, modified and understanded by any dev in any expertice level. For example, I'm pretty sure that a Junior JS dev with less than 6 months working on JS is gonna understand what is happening there.
So, the current original code is a bit more "KISS" than your proposal, and due to the goal of this lib is Keep things simple, I believe that we should keep it in this way.
Anyway, I'm open to continue talking about your proposal and try to find a middle point between your proposal and mine.

So, please, I'll be waiting for your answer about why do thing that we should implement your idea.
Thank you so much for taking the time to write that code!

**Comment by SaulDoesCode** [comment]
Sorry for the spontaneity and lack of elaboration with this, I wrote that code late last night after looking at your source. I've toyed with state managers for a good while and feel that so many of these purely functional approaches really complicate things more than necessary. Mutability is not an evil thing, it is necessary and happens everywhere naturally, the difficulty lies in the way it is consumed and the abstractions that come with that. There's too much abstraction for abstraction's sake, a kind of post-modern problem even in programming. The key/value system or single source of truth paradigm has really worked out the best for me in web projects because most apps get on fine with that, and just by adding (to a k/v store) some buckets/collections/spaces you already gain a degree of encapsulation/separation. I mean graph databases are often implemented purely as an abstraction over a K/V store. so yeah, it's a really good idea you've got going on here, with good composability as your examples show.

Just a thought, though, but you might want to avoid making your state manager a singleton, allow instances perhaps by separating out the different components.

anyhoo feel free to close this issue, as it is a non-issue really, I just put it here for you to see a different approach to the state problem. Ah, but state management is really hard, I've given up on it it's just so tricky because sometimes even a good abstraction ends up being too verbose. Plain objects already have mutability and getters/setters, and, with the addition of ``Proxy`` it's really easy to make amazingly flexible and intuitive APIs by intercepting things. It's just getting state to scale that's super hard.

here are some of my previous attempts at a state manager:
* [Schtat](https://github.com/SaulDoesCode/schtat) <- failure, but theoretically, my best
* [crafter-observable](https://github.com/SaulDoesCode/craft-observable)
* [SuperModel.js](https://github.com/SaulDoesCode/SuperModel.js) <- my practical best, not the best theoretically.

**Comment by BrodaNoel** [comment]
I absolutely agree with all what you say.
Most of the proposals currently are unnecessarily complex.

If someone doesn't like Mutability, so, justs don't mutate the data and that's all. It's not necessary to add the Unmutability in State Manager libs. That's why I didn't add it.

Again, thank you for your proposal/idea. I'll close this issue just to keep the issue list clean, but the labels still there, so if I need to find it again, it's gonna be easy.

Thank you so much!
