### ISSUE TITLE
The original ideia is that duix only has support to global scope?

### ISSUE THREAD

**Issue by atilacamurca** [BrodaNoel/duix#6]
I'm not saying is right or wrong, I'm just curious.

**Comment by BrodaNoel** [comment]
@atilacamurca global scope works in another way.
Let's suppose you have a variable called `name` in the global scope, and you want to execute the function `showName` every time `name` is called (and you don't know where, when, or who change this value).
How do you do it with no `duix`?

You need some listeners waiting for a change in `name`. Well, `duix` is that kind of listener. The only difference is that you don't set `name` in the global scope. Instead, you set `name` in `duix` (`duix.set('name', 'Noel')`)

**Comment by atilacamurca** [comment]
Got it.

Although, my concern was about the `store` object acting like a global scope. With `duix` I can't have two different sets of values in the same `key`, eg. `name`. In other state managers we usually see that they export a function, so we can possibly create multiple stores. But, at the same time, this kind of approach leads to the issues you describe when put variables in the global scope.

> ... you don't know where, when, or who change this value).

Anyway, this seems like a great library, and I'm looking forward to use in any of my projects.

**Comment by BrodaNoel** [comment]
@atilacamurca exactly. You are absolutely right. Currently, `duix` does not support multiples stores, or multiples instances. Why? Because `KISS`. I want to keep it simple. 100% simple.
There are not that many situations where your architecture requires multiples stores instances.
If you check the library README, it says that the `duix` approach is to solve those simple apps where you just need to share some values between components and no more than that.

If you really need multiples store instances, I'd recommend you to use another library. And I'm also gonna recommend you to NOT use multiples stores instances. Keep things simple, if you can.

If I need to simulate multiples stores, I'd just prepend a key, like:
* `duix.set('USER_name')`
* `duix.set('USER_surname')`
* `duix.set('TOPICS_first_category')`
* `duix.set('TOPICS_second_category')`

I never had the necessity of split stores in a semantic way. I'd can't imagine that necessity in simple projects. That's why `duix` currently doesn't support it.
